import { Action, Phase, SpecialistName } from '~/shared_types';
import { ServerConstants } from '~/server_types';

const serverConstants: ServerConstants = {

    SPECIALISTS: [
        {
            name: SpecialistName.advisor,
            displayName: 'Advisor',
            startingFavor: 1,
            specialty: 'linen',
            description: 'May donate commodities to the Temple using any Market contract.',
        },
        {
            name: SpecialistName.ambassador,
            displayName: 'Ambassador',
            startingFavor: 0,
            specialty: null,
            description: 'Begins with fully upgraded cargo hold.',
        },
        {
            name: SpecialistName.chancellor,
            displayName: 'Chancellor',
            startingFavor: 1,
            specialty: 'gems',
            description: 'May substitute goods with Favor when trading at the market.',
        },
        {
            name: SpecialistName.harbormaster,
            displayName: 'Harbormaster',
            startingFavor: 2,
            specialty: 'marble',
            description: 'May perform actions after first and second move after spending Favor.',
        },
        {
            name: SpecialistName.moneychanger,
            displayName: 'Moneychanger',
            startingFavor: 2,
            specialty: 'linen',
            description : 'May perform Market actions at the Temple instead of donating commodities.',
        },
        {
            name: SpecialistName.navigator,
            displayName: 'Navigator',
            startingFavor: 1,
            specialty: 'ebony',
            description: 'May cross barriers when moving. When doing so, no influence check is made.',
        },
        {
            name: SpecialistName.priest,
            displayName: 'Priest',
            startingFavor: 2,
            specialty: 'marble',
            description: 'Gains Favor after voluntarily ending the turn at the Temple.',
        },
        {
            name: SpecialistName.temple_guard,
            displayName: 'Temple Guard',
            startingFavor: 2,
            specialty: 'ebony',
            description: 'Adds 1 to influence checks (up to 6).',
        },
        {
            name: SpecialistName.postmaster,
            displayName: 'Postmaster',
            startingFavor: 1,
            specialty: 'gems',
            description: 'May donate metals to the Temple from an adjacent sea zone.',
        },
        {
            name: SpecialistName.peddler,
            displayName: 'Peddler',
            startingFavor: 2,
            specialty: null,
            description: 'Ignores one required trade good when completing a reduced value market trade.',
        }, // TODO: implement Peddler
    ],
    TRADE_DECK_A: [
        { request: ['ebony'], reward: { coins: 1, favorAndVp: 1 } },
        { request: ['ebony', 'ebony'], reward: { coins: 3, favorAndVp: 3 } },
        { request: ['ebony', 'gems'], reward: { coins: 3, favorAndVp: 2 } },
        { request: ['ebony'], reward: { coins: 1, favorAndVp: 1 } },
        { request: ['ebony', 'gems', 'linen'], reward: { coins: 5, favorAndVp: 3 } },
        { request: ['gems'], reward: { coins: 2, favorAndVp: 1 } },
        { request: ['gems'], reward: { coins: 2, favorAndVp: 1 } },
        { request: ['gems', 'linen'], reward: { coins: 3, favorAndVp: 2 } },
        { request: ['linen'], reward: { coins: 1, favorAndVp: 1 } },
        { request: ['gems', 'marble'], reward: { coins: 3, favorAndVp: 3 } },
        { request: ['ebony', 'marble', 'linen'], reward: { coins: 4, favorAndVp: 4 } },
        { request: ['ebony', 'linen'], reward: { coins: 3, favorAndVp: 3 } },
        { request: ['ebony', 'marble'], reward: { coins: 2, favorAndVp: 3 } },
        { request: ['marble'], reward: { coins: 1, favorAndVp: 2 } },
        { request: ['linen'], reward: { coins: 1, favorAndVp: 1 } },
        { request: ['marble', 'marble'], reward: { coins: 3, favorAndVp: 4 } },
        { request: ['gems', 'gems'], reward: { coins: 4, favorAndVp: 3 } },
        { request: ['marble'], reward: { coins: 1, favorAndVp: 2 } },
        { request: ['marble', 'linen'], reward: { coins: 2, favorAndVp: 3 } },
        { request: ['ebony', 'linen'], reward: { coins: 2, favorAndVp: 2 } },
    ],
    TRADE_DECK_B: [
        { request: ['ebony'], reward: { coins: 2, favorAndVp: 1 } },
        { request: ['gems', 'marble', 'linen'], reward: { coins: 5, favorAndVp: 4 } },
        { request: ['linen', 'linen'], reward: { coins: 3, favorAndVp: 3 } },
        { request: ['ebony', 'gems'], reward: { coins: 4, favorAndVp: 2 } },
        { request: ['ebony', 'linen'], reward: { coins: 2, favorAndVp: 2 } },
        { request: ['marble', 'linen'], reward: { coins: 2, favorAndVp: 3 } },
        { request: ['ebony', 'marble'], reward: { coins: 3, favorAndVp: 3 } },
        { request: ['marble'], reward: { coins: 2, favorAndVp: 2 } },
        { request: ['linen'], reward: { coins: 2, favorAndVp: 1 } },
        { request: ['ebony', 'ebony', 'linen'], reward: { coins: 5, favorAndVp: 4 } },
        { request: ['gems'], reward: { coins: 2, favorAndVp: 1 } },
        { request: ['linen'], reward: { coins: 2, favorAndVp: 1 } },
        { request: ['gems', 'marble'], reward: { coins: 4, favorAndVp: 3 } },
        { request: ['ebony', 'marble', 'linen'], reward: { coins: 4, favorAndVp: 4 } },
        { request: ['ebony', 'gems', 'marble'], reward: { coins: 6, favorAndVp: 4 } },
        { request: ['gems', 'gems', 'ebony'], reward: { coins: 7, favorAndVp: 4 } },
        { request: ['ebony'], reward: { coins: 2, favorAndVp: 1 } },
        { request: ['ebony', 'ebony'], reward: { coins: 4, favorAndVp: 3 } },
        { request: ['gems', 'gems'], reward: { coins: 5, favorAndVp: 3 } },
        { request: ['marble'], reward: { coins: 2, favorAndVp: 2 } },
        { request: ['marble', 'marble'], reward: { coins: 4, favorAndVp: 4 } },
        { request: ['linen', 'linen', 'gems'], reward: { coins: 6, favorAndVp: 4 } },
        { request: ['gems', 'linen'], reward: { coins: 3, favorAndVp: 2 } },
        { request: ['gems'], reward: { coins: 2, favorAndVp: 1 } },
    ],
    DEFAULT_MOVE_RULES: [
        { from: 'center', allowed: ['topRight', 'right', 'bottomRight', 'bottomLeft', 'left', 'topLeft'], blockedBy: [2, 4, 6, 8, 10, 12] },
        { from: 'topRight', allowed: ['center', 'right', 'topLeft'], blockedBy: [1, 2, 3] },
        { from: 'right', allowed: ['center', 'topRight', 'bottomRight'], blockedBy: [3, 4, 5] },
        { from: 'bottomRight', allowed: ['center', 'right', 'bottomLeft'], blockedBy: [5, 6, 7] },
        { from: 'bottomLeft', allowed: ['center', 'left', 'bottomRight'], blockedBy: [7, 8, 9] },
        { from: 'left', allowed: ['center', 'topLeft', 'bottomLeft'], blockedBy: [9, 10, 11] },
        { from: 'topLeft', allowed: ['center', 'left', 'topRight'], blockedBy: [1, 11, 12] },
    ],
    BARRIER_CHECKS: {
        1: { between: ['topLeft', 'topRight'], incompatible: [1, 11, 12, 2, 3] },
        2: { between: ['topRight', 'center'], incompatible: [1, 2, 3] },
        3: { between: ['topRight', 'right'], incompatible: [1, 2, 3, 4, 5] },
        4: { between: ['right', 'center'], incompatible: [3, 4, 5] },
        5: { between: ['right', 'bottomRight'], incompatible: [3, 4, 5, 6, 7] },
        6: { between: ['bottomRight', 'center'], incompatible: [5, 6, 7] },
        7: { between: ['bottomRight', 'bottomLeft'], incompatible: [5, 6, 7, 8, 9] },
        8: { between: ['bottomLeft', 'center'], incompatible: [7, 8, 9, 10] },
        9: { between: ['bottomLeft', 'left'], incompatible: [7, 8, 9, 10, 11] },
        10: { between: ['left', 'center'], incompatible: [9, 10, 11] },
        11: { between: ['left', 'topLeft'], incompatible: [9, 10, 11, 12, 1] },
        12: { between: ['topLeft', 'center'], incompatible: [11, 12, 1] },
    },
    PLAYER_IDS: [
        'Purple',
        'Yellow',
        'Red',
        'Green',
    ],
    LOCATION_ACTIONS: [
        { name: 'temple', actions: [Action.upgrade_cargo, Action.donate_goods, Action.donate_metal] },
        { name: 'market', actions: [Action.sell_goods, Action.sell_specialty] },
        { name: 'treasury', actions: [Action.buy_metal] },
        { name: 'quarry', actions: [Action.load_good] },
        { name: 'forest', actions: [Action.load_good] },
        { name: 'mines', actions: [Action.load_good] },
        { name: 'farms', actions: [Action.load_good] },
    ],
    LOCATION_GOODS: {
        quarry: 'marble',
        forest: 'ebony',
        mines: 'gems',
        farms: 'linen',
    },
    DEFAULT_NEW_STATE: {
        gameId: 'default',
        sessionPhase: Phase.enrolment,
        sessionOwner: null,
        chat: [],
        availableSlots: [
            'Purple',
            'Yellow',
            'Red',
            'Green',
        ],
        players: [],
    },
    COST_TIERS: [
        {
            templeLevel: 0,
            skipOnPlayerCounts: [2, 3],
            treasury: { goldCost: { coins: 2, favor: 5 }, silverCost: { coins: 1, favor: 3 } },
        },
        {
            templeLevel: 1,
            skipOnPlayerCounts: [],
            treasury: { goldCost: { coins: 3, favor: 5 }, silverCost: { coins: 1, favor: 3 } },
        },
        {
            templeLevel: 2,
            skipOnPlayerCounts: [],
            treasury: { goldCost: { coins: 4, favor: 5 }, silverCost: { coins: 2, favor: 3 } },
        },
        {
            templeLevel: 3,
            skipOnPlayerCounts: [],
            treasury: { goldCost: { coins: 5, favor: 5 }, silverCost: { coins: 2, favor: 3 } },
        },
        {
            templeLevel: 4,
            skipOnPlayerCounts: [],
            treasury: { goldCost: { coins: 6, favor: 5 }, silverCost: { coins: 3, favor: 3 } },
        },
        {
            templeLevel: 5,
            skipOnPlayerCounts: [2],
            treasury: { goldCost: { coins: 7, favor: 5 }, silverCost: { coins: 4, favor: 3 } },
        },
    ],
};

export default serverConstants;